### ISSUE TITLE
Firefox on macOS

### ISSUE THREAD

**Issue by cheginit** [AmadeusWM/dotfiles-hyprland#1]
Although your rice is for Linux, but I used the Firefox theme and everything seem to work except for the close/min/max buttons that are overlaid on top of the back/forward.
<img width="257" alt="image" src="https://user-images.githubusercontent.com/13016644/205175096-34f1f9f6-76c2-46f1-83f2-5076abb3a423.png">

**Comment by AmadeusWM** [comment]
Hi, thanks for posting an issue. This is something which you'll have to patch yourself, because it would cause an ugly padding for the linux users. (image)
![image](https://user-images.githubusercontent.com/63149896/205212735-5907e2bb-5e40-489b-ac40-b9af8218c3bc.png)
But I can tell you how to fix it, and I will add it to the readme :)
Do the following:
1. Open this file in your editor: `dotfiles-hyprland/dots/firefox/chrome/window-controls/wc-without-tabline.css`
2. Uncomment the following: (in `:root:not([inFullscreen]) toolbar#nav-bar`
```css
margin-left: calc(
        var(--wc-right-space) * 2 + 60px
    ) !important; 
```
3. Comment in this line:
```css
margin-left: 0px;
```
4. Your file should look like this
```css
@import "window-controls.css";

:root:not([inFullscreen]) toolbar#nav-bar {
    z-index: 1 !important;
    position: relative !important;
    /* shift toolbar to the right based on initial width */
    margin-left: calc(
        var(--wc-right-space) * 2 + 60px
    ) !important; 
    /* margin-left: 0px; */
}

#TabsToolbar .toolbar-items {
    display: none !important;
}

.titlebar-buttonbox {
    flex-direction: row-reverse;
}

#TabsToolbar.browser-toolbar {
    display: inline-block !important;
    position: absolute;
    top: var(--wc-vertical-shift) !important;
    left: var(--wc-left-space) !important;
}
```
This should fix your issue
