### ISSUE TITLE
Firefox on windows

### ISSUE THREAD

**Issue by AlexMe2** [AmadeusWM/dotfiles-hyprland#2]
hello there, i installed your firefox theme on windows and i don't have window-control-buttons, i tried the macOS fix but it doesn't work

**Comment by AmadeusWM** [comment]
Okay, I hopped on windows rq.
The solution is to add replace this line: (in `chrome/config.css`)
```css
@import "window-controls/wc-without-tabline.css";
```
with the following:
```css
@import "window-controls/wc-without-tabline-r.css";
```
Afterwards your buttons will probably be visible, but they will be squared. You can solve that by going to `chrome/windowj-controls/window-controls.css`. And adding this line to the `.titlebar-button` class:
```css
border-radius: 20px;
```
Resulting in something like this:
```css
.titlebar-button {
    transition: all 0.1s ease !important;
    padding: 0px 8px !important;
    background: none !important;
    -moz-context-properties: fill, fill-opacity !important;
    width: 16px;
    height: 16px;
    margin-left: 10px !important;
    border-radius: 20px;
}
```
Hope this helps. I'll add it to the readme.
